apiVersion: v1
kind: Service
metadata:
  name: {{ include "urchart.fullname" . }}
  labels:
   app: {{.Values.service.serviceLabel}}
   job: {{.Values.service.jobName}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "urchart.selectorLabels" . | nindent 4 }}
